name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: App - install dependencies
      working-directory: app
      run: npm install

    - name: App - Run the tests
      working-directory: app
      run: npm run test:ci

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
          files: ./app/coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}