on:
  workflow_dispatch:
    inputs:
      activityid:
        description: 'Activity ID'
        required: true
        type: number
      distance:
        description: 'Distance'
        required: true 
        type: number
      movingtime:
        description: 'Moving Time'
        type: number
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install node dependencies
      run: npm install
      working-directory: gh-action-scripts
    - name: Store Activity
      working-directory: gh-action-scripts
      run: npm run store-activity
         --activityid=${{ github.event.inputs.activityid }}
         --distance=${{ github.event.inputs.distance }}
         --movingtime=${{ github.event.inputs.movingtime }}
    - name: Commit and push
      run: |-
        git diff
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "gh action bot"
        git add -A
        git commit -m "storeActivity ${{ github.event.inputs.activityid }}"
        git push