name: Update YTD History

on:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install node dependencies
      run: npm ci
      working-directory: github-actions
    - name: Compile Typescript
      run: npm run build
      working-directory: github-actions
    - name: Update YTD History
      id: update-ytd
      working-directory: github-actions
      run: npm run update-ytd-history
    - name: Commit and push
      run: |-
        git diff
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "gh action bot"
        git add -A
        git commit -m "🗂 Update ytd history (v${{ steps.update-ytd.outputs.ytdVersion }})"
        git push