name: Update Athlete YTD

on:
  workflow_dispatch:
    inputs:
      athleteid:
        description: 'Athlete ID'
        required: true
        type: number
      count:
        description: 'Count'
        type: number
        required: true
      distance:
        description: 'Distance'
        required: true 
        type: number
      movingtime:
        description: 'Moving Time'
        type: number
        required: true
      elevationgain:
        description: 'Elevation Gain'
        type: number
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: '22.x'
    - name: Install node dependencies
      run: npm ci
      working-directory: github-actions
    - name: Compile Typescript
      run: npm run build
      working-directory: github-actions
    - name: Update Current Athlete YTD
      working-directory: github-actions
      run: npm run update-current-ytd
         --athleteid=${{ github.event.inputs.athleteid }}
         --count=${{ github.event.inputs.count }}
         --distance=${{ github.event.inputs.distance }}
         --movingtime=${{ github.event.inputs.movingtime }}
         --elevationgain=${{ github.event.inputs.elevationgain }}