on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install node dependencies
      run: npm install
      working-directory: gh-action-scripts
    - name: Update Current YTD
      working-directory: gh-action-scripts
      run: npm run update-ytd